### ISSUE TITLE
UP主,脚本运行失败，求指导下

### ISSUE THREAD

**Issue by xiyanxiyan10** [lzjun567/django_blog#22]
/home/ubuntu/env/django_blog/bin/gunicorn

失败原因在于脚本会加载这个文件，而virtualenv并不会生成这个，求该文件是否是工程中拷贝过去的

**Comment by lzjun567** [comment]
没安装gunicorn吧？

`pip install gunicorn`

**Comment by xiyanxiyan10** [comment]
收到~

**Comment by xiyanxiyan10** [comment]
谢谢,解决啦
